/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugas1;

/**
 *
 * @author Cordovix-ME
 */
public class Frame1 extends javax.swing.JFrame {

    /**
     * Creates new form Frame1
     */
    public Frame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        h1 = new javax.swing.JTextField();
        h2 = new javax.swing.JTextField();
        dis = new javax.swing.JTextField();
        h3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(h1);
        h1.setBounds(146, 40, 98, 20);
        getContentPane().add(h2);
        h2.setBounds(146, 66, 98, 20);
        getContentPane().add(dis);
        dis.setBounds(146, 120, 98, 20);
        getContentPane().add(h3);
        h3.setBounds(146, 94, 98, 20);

        jButton1.setText("Hitung!");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(156, 146, 67, 23);

        ta.setColumns(20);
        ta.setRows(5);
        jScrollPane1.setViewportView(ta);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(104, 187, 166, 96);

        jLabel1.setText("Barang 2");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(85, 69, 43, 14);

        jLabel2.setText("Barang 3");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(85, 97, 43, 14);

        jLabel3.setText("Barang 1");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(85, 43, 43, 14);

        jLabel4.setText("Diskon");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(97, 123, 31, 14);

        jLabel5.setText("TOKO SUKIR");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(146, 11, 244, 23);

        setBounds(0, 0, 416, 339);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int ha1 = Integer.parseInt(h1.getText());
        int ha2 = Integer.parseInt(h2.getText());
        int ha3 = Integer.parseInt(h3.getText());
        int d = Integer.parseInt(dis.getText());
        int th = ha1+ha2+ha3;
        int dc = d*th/100;
        int tb = th - dc;
        
         ta.setText(
                  "\nHarga Barang 1 = Rp."+ ha1
                 +"\nHarga Barang 2 = Rp."+ ha2
                 +"\nHarga Barang 3 = Rp."+ ha3
                 +"\nTotal Harga = Rp."+ th
                 +"\nDiskon = Rp."+ dc
                 +"\nTotal Pembayaran = Rp."+ tb
         
         );
        











        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dis;
    private javax.swing.JTextField h1;
    private javax.swing.JTextField h2;
    private javax.swing.JTextField h3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea ta;
    // End of variables declaration//GEN-END:variables
}
